myapp/user/routes.py
from flask import (Blueprint, request, render_template, redirect,
                    url_for, flash)
from myapp.models import User, Vehicle
from myapp import db
from flask_login import (login_user, logout_user, 
                            login_required, current_user)


user = Blueprint("user", __name__)


@user.route("/", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated and current_user.is_admin:
        return redirect("/admin")
    if current_user.is_authenticated:
        print(current_user.is_admin)
        return redirect(url_for('user.dashboard'))
    if request.method == "POST":
        email = request.form.get("email")
        password =  request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user==None:
            flash("No user registered with this email.", "danger")
            return redirect(url_for("user.login"))
        if user.password == password:
            login_user(user)
            if current_user.is_authenticated and current_user.is_admin:
                return redirect("/admin")
            return redirect(url_for('user.dashboard'))
        else:
            flash("Incorrect Password!", "warning")
            return redirect(url_for("user.login"))

    return render_template("login.html")


@user.route("/dashboard")
@login_required
def dashboard():
    if current_user.is_admin:
        return redirect(url_for("admin.index"))
    vehicle = Vehicle.query.filter_by(driver_id=current_user.id).first()
    return render_template("dashboard.html", vehicle=vehicle, 
                           dashboard="router-link-active")

@user.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("user.login"))

myapp/templates/sections/navbar.html
<style>
  .mynav{
    position: sticky !important;
    background-color: rgba(144, 238, 144, 0.3) !important; 
    box-shadow: inset 0 -1px 4px 0px rgba(0, 0, 0, 0.5);
  }
</style>




<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light mynav" style="width: 100%; display: flex;">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <!-- <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button> -->
  
      <!-- Collapsible wrapper -->
      <div class="navbar" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="/">
          <img src="{{ url_for('static', filename='css_images/logo.png') }}"
                      style="width: 100px;" alt="logo">
        </a>

      </div>

        <a href="{{ url_for('user.logout') }}"
        style="background-color: rgb(215, 13, 47); color: aliceblue;
        padding: 5px; margin-right: 10px;">Logout</a>


      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

myapp/templates/sections/vehicle_details.html
{% if vehicle %}
<h5>Current Vehicle Details</h5>
<table class="table table-sm">
<tbody>
    <tr>
        <td>Registration No.</td>
        <td>{{ vehicle.registration_no }}</td>
    </tr>
    <tr>
        <td>Financer</td>
        <td>{{ vehicle.financer }}</td>
    </tr>
    <tr>
        <td>Account No.</td>
        <td>{{ vehicle.account_no }}</td>
    </tr>
    <tr>
        <td>Original Capital Balance</td>
        <td>{{ vehicle.original_capital_balance }}</td>
    </tr>
    <tr>
        <td>Installment Amount</td>
        <td>{{ vehicle.installment_amount }}</td>
    </tr>
    <tr>
        <td>Frequency of installment</td>
        <td>{{ vehicle.frequency_of_installment }}</td>
    </tr>
    <tr>
        <td>Date Commenced</td>
        <td>{{ vehicle.date_commenced }}</td>
    </tr>
    <tr>
        <td>Expiry date</td>
        <td>{{ vehicle.expiry_date }}</td>
    </tr>
    <tr>
        <td>original_term</td>
        <td>{{ vehicle.original_term }}</td>
    </tr>
    <tr>
        <td>Remaining Installments</td>
        <td>{{ vehicle.remaining_installments }}</td>
    </tr>
    <tr>
        <td>Balloon / Risidual</td>
        <td>{{ vehicle.balloon_risidual }}</td>
    </tr>
    <tr>
        <td>Outstanding Capital Balance</td>
        <td>{{ vehicle.outstanding_capital_balance }}</td>
    </tr>
    <tr>
        <td>Advance Amount</td>
        <td>{{ vehicle.advance_amount }}</td>
    </tr>
    <tr>
        <td>Actual Contract Amount</td>
        <td>{{ vehicle.actual_contract_balance }}</td>
    </tr>
    <tr>
        <td>Interest Rate</td>
        <td>{{ vehicle.interest_rate }}%</td>
    </tr>
    <tr>
        <td>Take on odo</td>
        <td>{{ vehicle.take_on_odo }}</td>
    </tr>
    <tr>
        <td>Vehicle manufacturer</td>
        <td>{{ vehicle.vehicle_manufacturer }}</td>
    </tr>
    <tr>
        <td>Date of first registration</td>
        <td>{{ vehicle.date_of_first_registration }}</td>
    </tr>
    <tr>
        <td>model</td>
        <td>{{ vehicle.model }}</td>
    </tr>
    <tr>
        <td>Color</td>
        <td>{{ vehicle.color }}</td>
    </tr>
    <tr>
        <td>Mobile Number</td>
        <td>{{ vehicle.mobile_number }}</td>
    </tr>
    <tr>
        <td>Engine No.</td>
        <td>{{ vehicle.engine_no }}</td>
    </tr>
    <tr>
        <td>Vin no</td>
        <td>{{ vehicle.vin_no }}</td>
    </tr>
    <tr>
        <td>Tank Capacity</td>
        <td>{{ vehicle.tank_capacity }}</td>
    </tr>
    <tr>
        <td>License Disk Expiry Date (Y-M-D)</td>
        <td>{{ vehicle.license_disk_expiry_date }}</td>
    </tr>
    <tr>
        <td>License Disk Renewal Date (Y-M-D)</td>
        <td>{{ vehicle.license_disk_renewal_date }}</td>
    </tr>
    <tr>
        <td>Currently Assigned to: </td>
        <td>{{ current_user.username }}</td>
    </tr>

</tbody>
</table>

{% else %}

<h1>No Vehicles to display</h1>

{% endif %}