myapp/driver_forms/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from myapp.models import (FleetCard, MaintenancesTyres, 
                          FleetIncidentReporting, FleetNcIncidentReporting, 
                          fleet_inspection_card_form, VehicleExpense)
from myapp import db, change_to_datetime
from datetime import datetime
from flask_login import current_user, login_required

driver_forms = Blueprint("driver_forms", __name__)

def convert_str_to_datetime_obj(date_str):
    dlist = date_str.split("-")
    myyear = dlist[0]
    mymonth = int(dlist[1])
    myday = int(dlist[2])
    final_date = datetime(year=int(myyear), month=mymonth,
        day=myday)
    
    return final_date




@driver_forms.route("/fleet_card_form", methods=["POST","GET"])
def fleet_card_form():
    fleet_card = FleetCard.query.filter_by(driver_id=current_user.id).first()
    is_available = False
    if fleet_card:
        is_available = True

    if request.method=="POST":
        registration_no = request.form.get("registration_no")
        driver_name = request.form.get("driver_name")
        take_on_odo =request.form.get("take_on_odo")
        vehicle_manufacturer = request.form.get("vehicle_manufacturer")
        date_of_first_registration = request.form.get("date_of_first_registration")
        model_name = request.form.get("model_name")
        color_name = request.form.get("color_name")
        mobile_no = request.form.get("mobile_no")
        engine_no = request.form.get("engine_no")
        vin_no = request.form.get("vin_no")
        tank_capacity = request.form.get("tank_capacity")
        employee_no = request.form.get("employee_no")

        card = FleetCard(
            registration_no = registration_no,
            driver = driver_name,
            take_on_odo = take_on_odo,
            vehicle_manufacturer = vehicle_manufacturer,
            # date_of_first_registration = my_date_of_first_registration,
            date_of_first_registration = convert_str_to_datetime_obj(date_of_first_registration),

            model = model_name,
            color = color_name,
            mobile_number = mobile_no,
            engine_no = engine_no,
            vin_no = vin_no,
            tank_capacity = tank_capacity,
            employee_no = employee_no,
            driver_id = current_user.id,
        )

        db.session.add(card)
        db.session.commit()
    

    return render_template("driver_forms/fleet_card_order_form.html",
                fleet_card_class="router-link-active",
                        is_available = is_available)


@driver_forms.route("/maintenance_card_form",methods=["POST","GET"])
@login_required
def maintenance_card_form():
    maintanance = MaintenancesTyres.query.filter_by(driver_id=current_user.id).all()
    return render_template("driver_forms/maintenance.html",
            maintanance_card_class="router-link-active", maintanance=maintanance)
    
@driver_forms.route("/add_maintanance", methods=["GET", "POST"])
@login_required
def add_maintanance():
    if request.method=="POST":
        Driver_name = request.form.get("driver_name")
        reg_num = request.form.get("reg_num")
        yr_mth = request.form.get("yr_mth")
        make = request.form.get("make")
        Model = request.form.get("Model")
        Fuel_Value = request.form.get("Fuel_Value")
        Km_Travelled = request.form.get("Km_Travelled")
        oil_value = request.form.get("Oil_Value")
        km = request.form.get("km")
        Repair_and_Maint = request.form.get("Repair_and_Maint")
        Maintenance_Plan = request.form.get("Maintenance_Plan")

        maintenance_expiry_date = request.form.get("maintenance_expiry_date")

        Type_of_Service = request.form.get("Type_of_Service")
        Service_Intervals = request.form.get("Service_Intervals")
        Tyre_Value = request.form.get("Tyre_Value")
        Accident_Value = request.form.get("Accident_Value")
        Accident_Incident = request.form.get("Accident_Incident")
        Other_Value = request.form.get("Other_Value")
        Description = request.form.get("Description")
        Toll_Value = request.form.get("Toll_Value")

        tyres = MaintenancesTyres(
            driver_id = current_user.id,
            reg_num = reg_num,
            yr_mth = change_to_datetime(yr_mth),
            make = make,
            model = Model,
            fuel_value = Fuel_Value,
            km_travelled = Km_Travelled,
            oil_value = oil_value,
            km = km,
            repair_and_maint = Repair_and_Maint,
            maintenance_plan = Maintenance_Plan,

            maintenance_expiry_year_month_km_date = convert_str_to_datetime_obj(maintenance_expiry_date),

            type_of_service = Type_of_Service,
            service_intervals = Service_Intervals,
            tyre_value = Tyre_Value,
            accident_value = Accident_Value,
            accident_incident = Accident_Incident,
            other_value = Other_Value,
            description = Description,
            toll_value = Toll_Value,
        )
        
        # if current user has already a vehicle expense object 
        # then modify it, else add a new vehicle expense object.
        # cvh = VehicleExpense.query.filter_by(driver_id=current_user.id).first()
        # if cvh:
        #     cvh.fuel_value = int(Fuel_Value)
        #     cvh.oil_value = int(oil_value)
        #     cvh.repair_and_maint = int(Repair_and_Maint)
        #     cvh.tyre_value = int(Tyre_Value)
        #     cvh.accident_value = int(Accident_Value)
        #     cvh.other_value = int(Other_Value)
        #     cvh.toll_value = int(Toll_Value)
        #     cvh.vehicle_id = int()
        #     cvh.driver_id = int()
        
        
        # Adding expenses in total maintanance
        vh = VehicleExpense(
            fuel_value = int(Fuel_Value),
            oil_value = int(oil_value),
            repair_and_maint = int(Repair_and_Maint),
            tyre_value = int(Tyre_Value),
            accident_value = int(Accident_Value),
            other_value = int(Other_Value),
            toll_value = int(Toll_Value),
            vehicle_id = current_user.vehicle.id,
            driver_id = current_user.id
        )
        db.session.add(vh)
        db.session.add(tyres)
        db.session.commit()
        
        flash("Expense has been added.", "warning")
        return redirect(url_for('driver_forms.maintenance_card_form'))
        
    return render_template("driver_forms/add_maintanance.html",
            maintanance_card_class="router-link-active")


@driver_forms.route("/fleet_incident_table",methods=["POST","GET"])
@login_required
def fleet_incident_table():
    fleet_data = FleetIncidentReporting.query.filter_by(driver_id=current_user.id).all()
    return render_template("driver_forms/fleet_incident_table.html",
            fleet_incident_table_class="router-link-active", fleet_data= fleet_data)


@driver_forms.route("/fleet_incident_card_form",methods=["POST","GET"])
def fleet_incident_reporting_form():
    if request.method=="POST":
        driver = request.form.get("driver_name")
        id_number_1 = request.form.get("id_number")
        amount = request.form.get('amount')
        license_no_1 = request.form.get("License")
        date_issued_1 = request.form.get("Date Issued")
        code_1 = request.form.get("Code")
        endorsed_1 = request.form.get("endorsed")
        do_you_have_your_own_insurance = request.form.get("do_you_have")
        details_of_your_insurance = request.form.get("details")
        details_of_previous_accidents = request.form.get("details_2")
        registration_no_1 = request.form.get("Registration")
        milage = request.form.get("milage")
        make_1 = request.form.get("make")
        model_1 = request.form.get("model")
        reason_for_passenger_in_vehicle = request.form.get("details_3")
        is_the_passenger_a_employee = request.form.get("passenger_2")
        name_surname_of_passenger = request.form.get("name")
        id_no_attach_copy_of_id = request.form.get("number")
        address_1 = request.form.get("address")
        details_of_injury_is = request.form.get("details")
        names_and_surname_of_driver = request.form.get("full_name")
        contact_details = request.form.get("contact")
        id_number_2 = request.form.get("id_no")
        license_no_2 = request.form.get("license_2")
        date_issued_2 = request.form.get("date_issued")
        code = request.form.get("Code_2")
        endorsed = request.form.get("endorsed_2")
        address_2 = request.form.get("address")
        company_name = request.form.get("company")
        company_address = request.form.get("company address")
        contact_person = request.form.get("contact_person")
        telephone_no = request.form.get("telephone_no")
        email_address = request.form.get("email_2")
        registration_no_2 = request.form.get("registration_2")
        colour_1 = request.form.get("colour_2")
        make_2 = request.form.get("make_2")
        model_2 = request.form.get("model_2")
        registration_no_3 = request.form.get("registration_no_3")
        colour_2 = request.form.get("colour_2")
        make_3 = request.form.get("make_3")
        model_3 = request.form.get("model_3")
        details_of = request.form.get("details_of")
        saps_case_no = request.form.get("saps")
        take_photo_1 = request.files['file']
        take_photo_2 = request.files['file_2']
        manager_1 = request.form.get("manager")
        date_1 = request.form.get("date")
        time_1 = request.form.get("time")
        manager_2 = request.form.get("manager_2")
        date_2 = request.form.get("date_2")
        time_2 = request.form.get("time_2")


        reporting = FleetIncidentReporting(
            driver = driver,
            id_number_1 = id_number_1,
            amount = amount,
            license_no_1 = license_no_1,

            # date_issued_1 = date_issued_1,

myapp/templates/driver_forms/add_maintanance.html
{% extends "layout.html" %} 

{% block body %}
   
<div class="main">
    <div class="card">
      <div class="card-body">
        
        <div class="header d-flex flex-row justify-content-between">
        <h4>Maintenance and Tyres</h4>
        <button onclick="history.back();"
         class="btn btn-outline-dark btn-sm ">Go Back</button>
      </div>
        <form
          action="{{ url_for('driver_forms.add_maintanance') }}"
          method="post"
          class="row g-3 needs-validation"
          enctype="multipart/form-data"
        >
          <div class="col-md-4">
            <label for="driver" class="form-label">Driver</label>
            <input type="text" class="form-control" id="driver"
               readonly value="{{ current_user.username }}"/>
          </div>
  
          <div class="col-md-4">
            <label for="reg_num" class="form-label">Employee no:<span class="text-danger">*</span>
              :</label>
            <input type="text" class="form-control" id="reg_num" name="reg_num"
             value="{{ current_user.employee_no }}"
              readonly/>
          </div>
  
          <div class="col-md-4">
            <label for="YR_MTH" class="form-label">YR MTH<span class="text-danger">*</span></label>
            <input type="date" name="yr_mth" class="form-control"id="YR_MTH"
              required/>
          </div>
  
          <div class="col-md-4">
            <label for="Make" class="form-label">Make</label>
            <input type="text" class="form-control" id="Make" name="make"
              value="{{ current_user.vehicle.vehicle_manufacturer }}" readonly/>
          </div>
  
          <div class="col-md-4">
            <label for="Model" class="form-label">Model</label>
            <input type="text" class="form-control" id="Model" name="Model"
              value="{{ current_user.vehicle.model }}" readonly/>
          </div>
  
          <div class="col-md-4">
            <label for="Fuel_Value" class="form-label">Fuel Value</label>
            <input type="number" class="form-control" id="Fuel_Value" name="Fuel_Value"/>
          </div>
  
          <div class="col-md-4">
            <label for="Km Travelled" class="form-label">Km Travelled:</label>
            <input type="number" class="form-control" id="Km Travelled" name="Km_Travelled"/>
          </div>
  
          <div class="col-md-4">
            <label for="Oil_Value" class="form-label">Oil Value</label>
            <input type="number" class="form-control" id="Oil_Value" name="Oil_Value"/>
          </div>
  
          <div class="col-md-4">
            <label for="km" class="form-label">Km</label>
            <input type="text" class="form-control" id="km" name="km"/>
          </div>
  
          <div class="col-md-4">
            <label for="Repair_and_Maint" class="form-label">Repair and Maint</label>
            <input type="number" class="form-control" id="Repair_and_Maint" name="Repair_and_Maint"/>
          </div>
  
          <div class="col-md-4">
            <label for="Maintenance_Plan" class="form-label">Maintenance Plan</label>
            <input type="text" class="form-control" id="Maintenance_Plan" name="Maintenance_Plan"/>
          </div>
  
          <div class="col-md-4">
            <label for=" Maintenance_Expiry" class="form-label">Maintenance Expiry Year/Month/Km</label>
            <input type="date" class="form-control" id=" Maintenance_Expiry" name="maintenance_expiry_date"/>
          </div>
  
          <div class="col-md-4">
            <label for="Type_of_Service" class="form-label">Type of Service</label>
            <input type="text" class="form-control" id="Type_of_Service" name="Type_of_Service"/>
          </div>

          <div class="col-md-4">
            <label for="Service_Intervals" class="form-label">Service Intervals</label>
            <input type="text" class="form-control" id="Service_Intervals" name="Service_Intervals"/>
          </div>

          <div class="col-md-4">
            <label for="Tyre_Value" class="form-label">Tyre Value</label>
            <input type="number" class="form-control" id="Tyre_Value" name="Tyre_Value"/>
          </div>

          <div class="col-md-4">
            <label for="Accident_Value" class="form-label">Accident Value</label>
            <input type="number" class="form-control" id="Accident_Value" name="Accident_Value"/>
          </div>

          <div class="col-md-4">
            <label for="Accident/Incident no/Driver" class="form-label">Accident/Incident no/Driver</label>
            <input type="number" class="form-control" id="Accident/Incident no/Driver" name="Accident_Incident"/>
          </div>

          <div class="col-md-4">
            <label for="Other_Value" class="form-label">Other Value</label>
            <input type="number" class="form-control" id="Other_Value" name="Other_Value"/>
          </div>

          <div class="col-md-4">
            <label for="Description" class="form-label">Description</label>
            <input type="text" class="form-control" id="Description" name="Description"/>
          </div>

          <div class="col-md-4">
            <label for="Toll_Value" class="form-label">Toll Value</label>
            <input type="number" class="form-control" id="Toll_Value" name="Toll_Value"/>
          </div>

          <div class="col-12">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

myapp/templates/driver_forms/fleet_N.C_incident_reporting_form.html
{% extends "layout.html" %} 

{% block body %}
   
<div class="main">
    <div class="card">
      <div class="card-body">
        
        <div class="header d-flex flex-row justify-content-between">
          <h3>Non-Compliance Incident/Accident</h3>
          <button onclick="history.back();"
           class="btn btn-outline-dark btn-sm">Go Back</button>
        </div>

        <form
          action="{{ url_for('driver_forms.fleet_N_incident_reporting_form') }}"
          method="post"
          class="row g-3 needs-validation"
          enctype="multipart/form-data"
        >

        <div class="col-md-12">
          <h5>Details of Flowcentric Vehicle:</h5>
        </div>

          <div class="col-md-4">
            <label for="registration_no" class="form-label">Registration Number: </label>
            <input type="number" class="form-control" id="registration_no"
              name="registration_no"/>
          </div>
  
          <div class="col-md-4">
            <label for="vin" class="form-label">VIN NO:</label>
            <input type="number" class="form-control" id="vin" name="vin"/>
          </div>
  
          <div class="col-md-4">
            <label for="make" class="form-label">Make & MODEL</label>
            <input type="text"class="form-control"id="make" name="make"/>
          </div>
  
          <div class="col-md-4">
            <label for="year" class="form-label">YEAR MODEL</label>
            <input type="text" class="form-control" id="year" name="vehicle_manufacturer"/>
          </div>

          <div class="col-md-12">
            <h5 style="text-decoration:underline ;">FULL NAMES AND SURNAME OF DRIVER RESPONSIBLE FOR DAMAGE</h5>
          </div>
  
          <div class="col-md-12">
            <h5>ID Number</h5>
          </div>
  
          <div class="col-md-12">
            <h5>Driver's License</h5>
          </div>

          <div class="col-md-4">
            <label for="license" class="form-label">NO:</label>
            <input type="number" class="form-control" id="license" name="License"/>
          </div>
  
          <div class="col-md-4">
            <label for="Date Issued" class="form-label">Date Issued:</label>
            <input type="date" class="form-control" id="Date Issued" name="date_issued"/>
          </div>
  
          <div class="col-md-4">
            <label for="Code" class="form-label">Code:</label>
            <input type="text" class="form-control" id="Code" name="code"/>
          </div>
  
          <div class="col-md-4">
            <label for="endorsed" class="form-label">Endorsed</label>
            <select id="endorsed" class="form-control" name="endorsed">
                <option value="Yes" selected>Yes</option>
                <option value="No">No</option>
            </select>
          </div>


          <div class="col-md-12">
            <h5 style="text-decoration:underline ;">FULL NAMES AND SURNAME OF DRIVER/PERSON REPORTING DAMAGE:</h5>
          </div>
  
          <div class="col-md-12">
            <h5>ID Number</h5>
          </div>
  
          <div class="col-md-12">
            <h5>Driver's License</h5>
          </div>

          <div class="col-md-4">
            <label for="license_2" class="form-label">NO:</label>
            <input type="number" class="form-control" id="license_2" name="License_2"/>
          </div>
  
          <div class="col-md-4">
            <label for="Date Issued_2" class="form-label">Date Issued:</label>
            <input type="date" class="form-control" id="Date Issued_2" name="date_issued_2"/>
          </div>
  
          <div class="col-md-4">
            <label for="Code_2" class="form-label">Code: B</label>
            <input type="text" class="form-control" id="Code_2" name="Code_2"/>
          </div>
  
          <div class="col-md-4">
            <label for="endorsed_2" class="form-label">Endorsed</label>
            <select id="endorsed_2" class="form-control" name="endorsed_2">
                <option value="Yes" selected>Yes</option>
                <option value="No">No</option>
            </select>
          </div>

          <div class="col-md-12">
            <h4 style="text-decoration:underline;">WHEN WAS THE DAMAGE DISCOVERED?</h4>
          </div>

          <div class="col-md-12">
            <h4 style="text-decoration:underline;">AMOUNT OF DAMAGE:</h4>
            <input type="number" class="form-control" id="demage" name="demage"/>
          </div>

          <div class="col-md-12">
            <h4 style="text-decoration:underline;">DETAILS OF DAMAGE:</h4>
            <div class="col-md-12">
              <textarea class="form-control" id="Details_2" cols="20" rows="1" name="demage_2"></textarea>
            </div>
          </div>

          <div class="col-md-12">
            <h4 style="text-decoration:underline;">DAMAGE RECOVERY SUGGESTION:</h4>
          </div>

          <div class="col-md-12">
            <h5>Damage Recovery Approved</h5>
          </div>

          <div class="col-md-12">
            <h3 style="text-decoration:underline; margin-top: 20px;">Reporting:</h3>
          </div>

          <div class="col-md-12">
            <h5>Was the Accident/Incident to the responsible Line Manager?</h5>
          </div>

          <div class="col-md-4">
            <label for="yes/no" class="form-label">YES/NO</label>
            <select id="yes/no" class="form-control" name="yes_no">
                <option value="EMAIL" selected>----</option>
                <option value="EMAIL">EMAIL</option>
                <option value="TELEPHONE">TELEPHONE</option>
            </select>
          </div>

          <div class="col-md-4">
            <label for="manager" class="form-label">Manager:</label>
            <input type="text" class="form-control" id="manager" name="manager"/>
          </div>
  
          <div class="col-md-4">
            <label for="date" class="form-label">Date:</label>
            <input type="date" class="form-control" id="date" name="date"/>
          </div>
  
          <div class="col-md-4">
            <label for="time" class="form-label">Time:</label>
            <input type="time" class="form-control" id="time" name="time"/>
          </div>
  
          <div class="col-md-12">
            <h5>Was the Accident/Incident to the responsible Fleet Manager?</h5>
          </div>

          <div class="col-md-4">
            <label for="yes/no_2" class="form-label">YES/NO</label>
            <select id="yes/no_2" class="form-control" name="yes_no_2">
                <option value="EMAIL" selected>----</option>
                <option value="EMAIL">EMAIL</option>
                <option value="TELEPHONE">TELEPHONE</option>
            </select>
          </div>

          <div class="col-md-4">
            <label for="manager_2" class="form-label">Manager:</label>
            <input type="text" class="form-control" id="manager_2" name="manager_2"/>
          </div>
  
          <div class="col-md-4">
            <label for="date_2" class="form-label">Date:</label>
            <input type="date" class="form-control" id="date_2" name="date_2"/>
          </div>
  
          <div class="col-md-4">
            <label for="time_2" class="form-label">Time:</label>
            <input type="time" class="form-control" id="time_2" name="time_2"/>
          </div>

          
          <!-- <div class="col-md-12" style="margin-top:30px;">
            <p>Karlilen Janse van Vuuren
              Fleet Manager</p>
              <h3>Date:</h3>
          </div> -->

       
          <div class="col-12">
            <button class="btn btn-primary" type="submit">Submit form</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

myapp/templates/driver_forms/fleet_card_order_form.html
{% extends "layout.html" %} 

{% block body %}

{% if is_available %}

<div class="main">
  <div class="card">
    <div class="card-body">
    
          <div class="alert alert-warning">
            You already submitted a form.
          </div>
    </div>
  </div>
</div>

{% endif %}

<div class="main">
    <div class="card">
      <div class="card-body">
        <h4>Fleet Card Order Form</h4>
        <form
          action="{{ url_for('driver_forms.fleet_card_form') }}"
          method="post"
          class="row g-3 needs-validation"
          enctype="multipart/form-data"
        >
          <div class="col-md-4">
            <label for="registration_no" class="form-label">Registration Number: </label>
            <input type="number" name="registration_no" class="form-control" id="registration_no"/>
          </div>
  
          <div class="col-md-4">
            <label for="name" class="form-label">Full Name and Surname</label>
            <input type="text" class="form-control" id="name" name="driver_name"/>
          </div>
  
          <div class="col-md-4">
            <label for="Take_on_Odo" class="form-label">Take on Odo:</label>
            <input type="text"class="form-control" name="take_on_odo" id="Take_on_Odo"/>
          </div>
  
          <div class="col-md-4">
            <label for="Vehicle_Manufacturer" class="form-label">Vehicle Manufacturer:</label>
            <input type="text" class="form-control" id="Vehicle_Manufacturer" name="vehicle_manufacturer"/>
          </div>
  
          <div class="col-md-4">
            <label for="date_of_first_registration" class="form-label">Date of First Registration:</label>
            <input type="date" class="form-control" id="date_of_first_registration" name="date_of_first_registration"/>
          </div>
  
          <div class="col-md-4">
            <label for="model" class="form-label">Model</label>
            <input type="text" class="form-control" id="model" name="model_name"/>
          </div>
  
          <div class="col-md-4">
            <label for="Colour" class="form-label">Colour:</label>
            <input type="text" class="form-control" id="Colour" name="color_name"/>
          </div>
  
          <div class="col-md-4">
            <label for="Mobile Number" class="form-label">Mobile Number:</label>
            <input type="number" class="form-control" id="Mobile Number" name="mobile_no"/>
          </div>
  
          <div class="col-md-4">
            <label for="Engine No" class="form-label">Engine No:</label>
            <input type="number" class="form-control" id="Engine No" name="engine_no"/>
          </div>
  
          <div class="col-md-4">
            <label for="Vin No" class="form-label">Vin No:</label>
            <input type="number" class="form-control" id="Vin No" name="vin_no"/>
          </div>
  
          <div class="col-md-4">
            <label for="Tank Capacity" class="form-label">Tank Capacity:</label>
            <input type="text" class="form-control" id="Tank Capacity" name="tank_capacity"/>
          </div>
  
          <div class="col-md-4">
            <label for="Employee Number" class="form-label">Employee Number:</label>
            <input type="number" class="form-control" id="Employee Number" name="employee_no" />
          </div>
  
          <div class="col-12">
            <button class="btn btn-primary"
            {% if is_available %}
                  disabled 
            {% endif %}
            
             type="submit">Submit form</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>
{% endblock body %}

myapp/templates/driver_forms/fleet_incident_table.html
{% extends "layout.html" %} 

{% block body %}
<style>
  body{
    overflow: scroll;
  }
</style>


<div class="main">
  <div class="card">
    <div class="card-body">

      {% include "_flash.html" %}

<div class="header d-flex flex-row justify-content-between">
  <h3>Fleet Incident Reports ({{fleet_data|count}})</h3>
  <a href="{{ url_for('driver_forms.fleet_incident_reporting_form') }}"
    class="btn btn-outline-info mb-2">Add Accident Roport</a>
</div>

<!-- Expense table for showing expenses -->
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="bg-dark text-white">
        <th>Driver</th>
        <th>Accident Amount</th>
        <th>Email Address</th>
        <th>Reporting Date</th>
        <th>Contact Person</th>
      </tr>
    </thead>
    <tbody>
      {% for f in fleet_data %}
      <tr>
        <td>{{ f.driver }}</td>
        <td>{{ f.amount }}</td>
        <td>{{ f.email_address }}</td>
        <td>{{ f.reporting_date_1 }}</td>
        <td>{{ f.contact_person }}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>
</div>



    </div>
  </div>
</div>



{% endblock %}

myapp/templates/driver_forms/maintenance.html
{% extends "layout.html" %} 

{% block body %}
<style>
  body{
    overflow: scroll;
  }
</style>


<div class="main">
  <div class="card">
    <div class="card-body">

      {% include "_flash.html" %}

      <div class="header d-flex flex-row justify-content-between">
        <h3>Total maintanance ({{maintanance|count}})</h3>
        <a href="{{ url_for('driver_forms.add_maintanance') }}"
         class="btn btn-outline-info mb-2">Add Maintanance</a>
      </div>

      <!-- Expense table for showing expenses -->
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr class="bg-dark text-white">
              <th>YR MTH</th>
              <th>Make</th>
              <th>Model</th>
              <th>Fuel Value</th>
              <th>KM Travelled</th>
              <th>Oil Value</th>
              <th>Km</th>
              <th>Repair and Maintanance</th>
              <th>Maintanace Plan</th>
              <th>Maintance Expire on</th>
              <th>Type of Service</th>
              <th>Service Interval</th>
              <th>Tyre Value</th>
              <th>Accident Value</th>
              <th>Accident Incident</th>
              <th>Other Value</th>
              <th>Description</th>
              <th>Toll Value</th>
            </tr>
          </thead>
          <tbody>
            {% for t in maintanance %}
            <tr>
              <td>{{ t.yr_mth.strftime("%Y-%m-%d") }}</td>
              <td>{{ t.make }}</td>
              <td>{{ t.model }}</td>
              <td>{{ t.fuel_value }}</td>
              <td>{{ t.km_travelled }}</td>
              <td>{{ t.oil_value }}</td>
              <td>{{ t.km }}</td>
              <td>{{ t.repair_and_maint }}</td>
              <td>{{ t.maintenance_plan }}</td>
              <td>{{ t.maintenance_expiry_year_month_km_date }}</td>
              <td>{{ t.type_of_service }}</td>
              <td>{{ t.service_intervals }}</td>
              <td>{{ t.tyre_value }}</td>
              <td>{{ t.accident_value }}</td>
              <td>{{ t.accident_incident }}</td>
              <td>{{ t.other_value }}</td>
              <td>{{ t.description }}</td>
              <td>{{ t.toll_value }}</td>
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>



    </div>
  </div>
</div>



{% endblock %}

myapp/templates/driver_forms/profile_page.html
{% extends "layout.html" %} 

{% block body %}

<div class="main">
    <div class="card">
        <div class="card-body">

            <!-- <center>
                <img src="{{ url_for('static', filename='css_images/user_logo.png') }}" alt="">
            </center> -->

<form action="{{ url_for('Admin_DriverVehicle.profile_page') }}" method="post" enctype="multipart/form-data">

<div class="col-md-12">
    <label for="file" class="form-label">Upload a Profile Photo</label>
    <input type="file" class="form-control" id="file" name="file1"/>
</div>

<div class="col-12">
    <button class="btn btn-primary mt-2" type="submit">Submit form</button>
</div>

</form>

</div>
</div>
</div>


{% endblock %}